-- Migration 003: Row Level Security Policies
-- Implement comprehensive RLS policies to protect data access

-- Enable Row Level Security on all tables
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_contact_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE check_ins ENABLE ROW LEVEL SECURITY;
ALTER TABLE missed_check_in_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE verification_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE sms_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE push_notification_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Users table policies
-- Users can read their own record
CREATE POLICY "Users can view own record"
  ON users FOR SELECT
  USING (auth.uid() = id);

-- Users can update their own record (except certain fields)
CREATE POLICY "Users can update own record"
  ON users FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Service role can do everything (for backend functions)
CREATE POLICY "Service role full access to users"
  ON users FOR ALL
  USING (auth.jwt()->>'role' = 'service_role')
  WITH CHECK (auth.jwt()->>'role' = 'service_role');

-- Members table policies
-- Users can read their own member profile
CREATE POLICY "Users can view own member profile"
  ON members FOR SELECT
  USING (auth.uid() = user_id);

-- Users can update their own member profile
CREATE POLICY "Users can update own member profile"
  ON members FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Contacts can view their members' profiles
CREATE POLICY "Contacts can view their members"
  ON members FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM member_contact_relationships
      WHERE member_contact_relationships.member_id = members.user_id
      AND member_contact_relationships.contact_id = auth.uid()
      AND member_contact_relationships.status = 'active'
      
    )
  );

-- Service role full access
CREATE POLICY "Service role full access to members"
  ON members FOR ALL
  USING (auth.jwt()->>'role' = 'service_role')
  WITH CHECK (auth.jwt()->>'role' = 'service_role');

-- Member-Contact Relationships table policies
-- Users can view relationships where they are either member or contact
CREATE POLICY "Users can view own relationships"
  ON member_contact_relationships FOR SELECT
  USING (
    auth.uid() = member_id OR auth.uid() = contact_id
  );

-- Contacts can create relationships (invitations)
CREATE POLICY "Contacts can create invitations"
  ON member_contact_relationships FOR INSERT
  WITH CHECK (auth.uid() = contact_id);

-- Users can update relationships where they are involved
CREATE POLICY "Users can update own relationships"
  ON member_contact_relationships FOR UPDATE
  USING (auth.uid() = member_id OR auth.uid() = contact_id)
  WITH CHECK (auth.uid() = member_id OR auth.uid() = contact_id);

-- Service role full access
CREATE POLICY "Service role full access to relationships"
  ON member_contact_relationships FOR ALL
  USING (auth.jwt()->>'role' = 'service_role')
  WITH CHECK (auth.jwt()->>'role' = 'service_role');

-- Check-ins table policies
-- Members can insert their own check-ins
CREATE POLICY "Members can create own check-ins"
  ON check_ins FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM members
      WHERE members.user_id = auth.uid()
      AND members.id = check_ins.member_id
    )
  );

-- Members can view their own check-ins
CREATE POLICY "Members can view own check-ins"
  ON check_ins FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM members
      WHERE members.user_id = auth.uid()
      AND members.id = check_ins.member_id
    )
  );

-- Contacts can view check-ins of their members
CREATE POLICY "Contacts can view members check-ins"
  ON check_ins FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM member_contact_relationships mcr
      JOIN members m ON m.user_id = mcr.member_id
      WHERE mcr.contact_id = auth.uid()
      AND m.id = check_ins.member_id
      AND mcr.status = 'active'
    )
  );

-- Service role full access
CREATE POLICY "Service role full access to check_ins"
  ON check_ins FOR ALL
  USING (auth.jwt()->>'role' = 'service_role')
  WITH CHECK (auth.jwt()->>'role' = 'service_role');

-- Missed check-in alerts table policies
-- Service role only (alerts generated by cron jobs)
CREATE POLICY "Service role full access to alerts"
  ON missed_check_in_alerts FOR ALL
  USING (auth.jwt()->>'role' = 'service_role')
  WITH CHECK (auth.jwt()->>'role' = 'service_role');

-- Verification codes table policies
-- Service role only (codes generated by auth endpoints)
CREATE POLICY "Service role full access to verification_codes"
  ON verification_codes FOR ALL
  USING (auth.jwt()->>'role' = 'service_role')
  WITH CHECK (auth.jwt()->>'role' = 'service_role');

-- SMS logs table policies
-- Service role only (logs created by backend)
CREATE POLICY "Service role full access to sms_logs"
  ON sms_logs FOR ALL
  USING (auth.jwt()->>'role' = 'service_role')
  WITH CHECK (auth.jwt()->>'role' = 'service_role');

-- Push notification tokens table policies
-- Users can view their own tokens
CREATE POLICY "Users can view own push tokens"
  ON push_notification_tokens FOR SELECT
  USING (auth.uid() = user_id);

-- Users can insert their own tokens
CREATE POLICY "Users can insert own push tokens"
  ON push_notification_tokens FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Users can delete their own tokens
CREATE POLICY "Users can delete own push tokens"
  ON push_notification_tokens FOR DELETE
  USING (auth.uid() = user_id);

-- Service role full access
CREATE POLICY "Service role full access to push_tokens"
  ON push_notification_tokens FOR ALL
  USING (auth.jwt()->>'role' = 'service_role')
  WITH CHECK (auth.jwt()->>'role' = 'service_role');

-- App notifications table policies
-- Users can view their own notifications
CREATE POLICY "Users can view own notifications"
  ON app_notifications FOR SELECT
  USING (auth.uid() = user_id);

-- Users can update their own notifications (mark as read)
CREATE POLICY "Users can update own notifications"
  ON app_notifications FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Service role full access
CREATE POLICY "Service role full access to app_notifications"
  ON app_notifications FOR ALL
  USING (auth.jwt()->>'role' = 'service_role')
  WITH CHECK (auth.jwt()->>'role' = 'service_role');

-- Audit logs table policies
-- Service role only (audit logs are append-only from backend)
CREATE POLICY "Service role full access to audit_logs"
  ON audit_logs FOR ALL
  USING (auth.jwt()->>'role' = 'service_role')
  WITH CHECK (auth.jwt()->>'role' = 'service_role');

-- Comments for documentation
COMMENT ON POLICY "Users can view own record" ON users IS 'Allow users to view their own user record';
COMMENT ON POLICY "Service role full access to users" ON users IS 'Backend functions use service role to bypass RLS';
COMMENT ON POLICY "Contacts can view their members" ON members IS 'Contacts can see profile information of their connected Members';
COMMENT ON POLICY "Contacts can view members check-ins" ON check_ins IS 'Contacts can view check-in history of their Members';
